### ISSUE TITLE
Attachments not working?

### ISSUE THREAD

**Issue by scratchyone** [xyaman/panda#2]
Attachments don't seem to be working on_message_create. It always gives an empty Vec

    client.on_message_create(|s, data| async move {
        if data.channel_id == CHANNEL {
            println!(
                "Message \"{}\" in {}\nattatchments: {:#?}",
                data.content, data.channel_id, data.attatchments
            );
        }
        Ok(())
    });

**Comment by xyaman** [comment]
Hi, I made a typo in `Message` struct, I wrote `attatchment` instead of `attachment`. I will patch this in a minutes, so will you have to update it in Cargo.toml. Thanks for reporting!

**Comment by xyaman** [comment]
Now it should work properly. Use version 0.5.2
