### ISSUE TITLE
Wrong argument type for `panda::client::Client::on_message_delete_bulk` ?

### ISSUE THREAD

**Issue by SlooowAndFurious** [xyaman/panda#3]
Tested with version 0.5.2 in crates.io.
The function `panda::client::Client::on_message_delete_bulk` seems to expect a wrong argument type : it waits for a function expecting a `panda::events::MessageDelete` structure but a `panda::events::MessageDeleteBulk` exists, so I'm wondering if the argument type is not wrong since it looks like a typo mistake. Moreover, the documentation says it "[sets] the handler for `MessageDeleteBulk` event".
Please, consider updating this function if I'm right.

**Comment by xyaman** [comment]
Thanks for reporting this!
