### ISSUE TITLE
How do I access update_status?

### ISSUE THREAD

**Issue by Nerothos** [xyaman/panda#5]
Hi,

I'm trying to use the function update_status but it can't seems to work.
I'm trying to get it from state or the session but since I'm using a custom one (see #1) maybe it's what posing problem here?

**Comment by xyaman** [comment]
Hi, update_status it's not in the last release, you can find in the master branch, and you find it as `session.update_status()`, but it's not complete yet, I guess I will finish it today.

**Comment by Nerothos** [comment]
Oh ok, I'll wait for it to drop then, thanks ;)

**Comment by xyaman** [comment]
Now you should be able to use `session.update_status()`, check this [example](https://github.com/xyaman/panda/blob/master/examples/status.rs).
