### ISSUE TITLE
Any way to get HttpClient from outside of bot event handlers?

### ISSUE THREAD

**Issue by Restioson** [xyaman/panda#8]
Is there any way to get an HttpClient for my bot except in the bot event handlers? I want to do this so that I can create a discord bridge to another chat application, which means that it needs to be able to send messages at arbitrary times, not triggered by discord events. Currently I see that you could wait for `on_ready` and set a mutable `Option<Arc<SessionData<S>>>` to `Some(data.clone())`, but is there any other way to do this?

**Comment by xyaman** [comment]
Hi, you can create a new `HttpClient` with [`panda::HttpClient::new("your token here")`](https://docs.rs/panda/0.5.3/panda/struct.HttpClient.html#method.new).

**Comment by Restioson** [comment]
Thanks.
